site_name: PictureLibrary-API Documentation
repo_url: https://github.com/TomaszKumiega/PictureLibrary-API
theme: 
    name: material
    palette:
        scheme: slate
        primary: teal
markdown_extensions:
  - codehilite
  - admonition
