site_name: API Documentation
repo_url: https://github.com/TomaszKumiega/PictureLibrary-API
theme:
  name: material
plugins:
  - search
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
