name: CD

on: push

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish image for Arm32
        id: docker_arm32_publish
        uses: docker/build-push-action@v2.2.1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          registry: docker.pkg.github.com
          repository: TomaszKumiega/PictureLibrary-API/picturelibraryapi-arm32
          file: ./arm32.Dockerfile
      - name: Publish default image
        id: docker_publish
        uses: docker/build-push-action@v2.2.1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          registry: docker.pkg.github.com
          repository: TomaszKumiega/PictureLibrary-API/picturelibraryapi
          file: ./dockerfile

