name: CD

on: push

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish image for Arm32
        id: docker_arm32_publish
        uses: elgohr/Publish-Docker-Github-Action@3.02
        with:
          name: picturelibraryapi-arm32
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          registry: docker.pkg.github.com
          dockerFile: arm32.Dockerfile
      - name: Publish default image
        id: docker_publish
        uses: elgohr/Publish-Docker-Github-Action@3.02
        with:
          name: picturelibraryapi
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          registry: docker.pkg.github.com
          dockerFile: dockerfile

