name: CD

on: push

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish image
        id: docker
        uses: matootie/github-docker@v2.2.2
        with:
          accessToken: ${{github.token}}
          buildArg: |
            VERSION=${{github.ref}}
            COMMIT=${{github.sha}}
      - name: Publish image for Arm32 architecture
        id: docker_Arm32
        uses: matootie/github-docker@v2.2.2
        with:
          accessToken: ${{github.token}}
          buildArg: |
            imageName: PictureLibraryAPI-arm32
            VERSION=${{github.ref}}
            COMMIT=${{github.sha}}
            contextName: dockerfileArm32

